name: arena_connect
description: "Arena Connect"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/background-image.png
    - images/arena-connect1.png
    - images/element.png
    - images/futsal1.jpg
    - images/futsal2.jpg
    - images/futsal3.jpg
    - images/badminton1.jpg
    - images/badminton2.jpg
    - images/badminton3.jpg
    - images/badminton.jpg
    - images/futsal.jpg
    - images/footballcup.jpg
    - images/badmintoncup.jpg
    - images/top-wave-cropped.png
    - images/lapangan-futsal.jpg
    - images/lapangan-badminton.jpg


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSans3-Regular.ttf
