name: arena_connect
description: "Arena Connect"
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.5.3

dependencies:
    carousel_slider: 5.0.0
    device_frame: 1.2.0
    device_preview: ^1.2.0
    flutter:
        sdk: flutter
    get: ^4.6.6
    http: ^1.2.2
    url_launcher: ^6.0.10

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
    image_picker: ^1.1.2

flutter:
    uses-material-design: true
    assets:
        - images/

    fonts:
        - family: Poppins
          fonts:
              - asset: fonts/Poppins-Regular.ttf
        - family: Source Sans Pro
          fonts:
              - asset: fonts/SourceSans3-Regular.ttf
