name: arena_connect
description: "Arena Connect"
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.5.3

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
    assets:
        - images/

    fonts:
        - family: Poppins
          fonts:
              - asset: fonts/Poppins-Regular.ttf
        - family: Source Sans Pro
          fonts:
              - asset: fonts/SourceSans3-Regular.ttf
